const projects=[
{id:'permission',title:'数据权限治理系统',type:'AI GOVERNANCE / 数据权限',category:'ai-governance',status:'已投入使用 · 运行 1 个月',proof:'73 类角色 / 416 个字段 / 首轮约 5 个字段校准',summary:'把业务权限从提示词约束，变成查询执行前可拦截、可审计的系统控制。',problem:'自然语言查数链路缺少稳定的字段级和行级权限。身份丢失、多角色叠加与自由 SQL 都可能造成越权。',work:['梳理岗位、字段敏感度与可见范围','设计 RBAC、ABAC、默认拒绝和查询前早拦','联调真实身份与查询链路，进行越权与绕过测试'],evidence:'完成 73 类真实系统角色映射与 416 个字段分级；系统投入使用后，根据真实反馈完成首轮约 5 个字段的权限校准。',boundary:'已投入使用 1 个月，并完成首轮权限校准。目前日常使用正常，整体反馈良好。',image:'assets/previews/permission.webp'},
{id:'ctc',title:'CTC 调拨系统',type:'BUSINESS SYSTEM / 供应链算法',category:'business-system',status:'真实试用',proof:'约 14 人天 → 约 30 分钟',summary:'用确定性业务算法，把库存、在途、需求和尺码约束转化为可配置、可比较的调拨方案。',problem:'人工调拨依赖多人表格与经验，难以稳定复现，也缺少运行审计和效果对照。',work:['独立负责业务逻辑、算法、数据接入、网页产品与测试','建立商品预测、Projected Stock、需求池和尺码分配规则','保留新旧算法双轨、审批状态与回滚路径'],evidence:'个人调整约 1 个月后进入团队试用，主体计算约 30 分钟。',boundary:'不能宣称完全替代 14 人天，人工复核与正式下单仍需单独计算。',image:'assets/previews/ctc.webp'},
{id:'otb',title:'OTB 管理产品',type:'BUSINESS SYSTEM / 商品经营',category:'business-system',status:'已部署使用',proof:'约 21 个真实查询接口',summary:'用真实数据与确定性口径，把预算、采购、销售、毛利、库存和调整审批放进同一决策界面。',problem:'计划、预算、订单和销售来自不同表格或系统，品牌口径不一致。',work:['统一关键指标口径并推动对数','支持采购组到品牌下钻、上传和版本记录','修复筛选分子错用全公司销售等严重口径问题'],evidence:'真实数据接入并部署，用于辅助买手买货。',boundary:'使用频率、被采纳动作和影响金额仍需持续记录。',image:'assets/previews/otb.webp'},
{id:'old-stock',title:'老货盘点系统',type:'BUSINESS SYSTEM / 商品运营',category:'business-system',status:'真实使用',proof:'约 2 周 → 3-4 天',summary:'用确定性查询与流程状态，把一次性盘点表转化为可持续跟进的老货经营工具。',problem:'业务人员难以同时看到库龄、库存、销售状态与后续动作。',work:['整合老货识别与商品明细','让业务人员直接查询并采取经营动作','把分散人工盘点转为可重复使用的工具'],evidence:'有真实业务人员使用，处理周期由约 2 周压缩到 3-4 天。',boundary:'实际使用人数、覆盖商品数和后续经营结果仍需补证。',image:'assets/previews/old-stock.webp'},
{id:'catalog',title:'商品目录',type:'BUSINESS SYSTEM / 商品信息',category:'business-system',status:'真实页面',proof:'图片、属性与到货统一检索',summary:'用结构化商品数据与多维筛选，降低“只有直接经手人知道货长什么样”的信息壁垒。',problem:'商品图片和属性散落，跨部门查找与沟通成本高。',work:['整合商品图片与关键属性','设计多维筛选与统一商品视图','规划商品表现和生命周期连接'],evidence:'已形成真实页面。',boundary:'覆盖 SPU 数、刷新频率和活跃用户仍需补证。',image:'assets/previews/catalog.webp'},
{id:'gap-radar',title:'品类缺口雷达',type:'AI-ASSISTED / 商品企划',category:'ai-assisted',status:'数据验证完成 · AI Workflow 设计中',proof:'3 个半年度 / 5 个品牌组',summary:'先用确定性计算找到结构缺口，再让 AI 基于证据解释原因、生成可审阅的机会假设。',problem:'企划判断容易依赖经验，外部市场数据又难取得且口径不一。',work:['建立品类、价格带与品牌组的透明缺口计算','完成总量、已知答案和复现检查','设计 AI 证据解释、置信分级与企划确认工作流'],evidence:'确定性缺口计算已覆盖 3 个半年度和 5 个品牌组；AI Workflow 为下一阶段方案。',boundary:'AI 只能解释证据并提出机会假设，不能把推断写成已验证需求；机会采用与经营结果仍待跟踪。',image:'assets/previews/gap-radar.webp'},
{id:'career-agent',title:'Career Agent',type:'AI WORKFLOW / 求职辅助',category:'ai-workflow',status:'可运行本地产品',proof:'发现 → 分析 → 确认 → 执行',summary:'把岗位采集、LLM 分析评分、人工确认、浏览器执行与日志留证串成一个可控的 AI Workflow。',problem:'求职者需要在多个平台重复搜索、阅读 JD、判断匹配度并编写沟通话术，过程耗时且容易遗漏。',work:['定义职业画像、评分模型和端到端状态机','实现岗位采集、LLM 分析、评分与话术生成','设计 Human-in-the-Loop、浏览器执行与全量日志'],evidence:'代码已覆盖智联与 BOSS 的浏览器采集、LLM 分析评分、人工确认后沟通，以及操作与模型日志。',boundary:'目前是个人本地产品，依赖招聘站点页面与登录状态；未作为公开平台上线，也不进行无人值守批量投递。'},
{id:'hive',title:'AI 项目与使用治理平台',type:'AI GOVERNANCE / 组织治理',category:'ai-governance',status:'一期登记闸门完成',proof:'约 31 个项目 / 六阶段治理',summary:'先让 AI 项目有入口、责任人与状态，再逐步连接使用透明、成本记录、风险识别和退出机制。',problem:'内部 AI 项目分散推进时，管理者难以持续知道谁在负责、是否真实使用、成本是否合理，以及何时继续或退出。',work:['设计六阶段治理框架与项目准入逻辑','完成登记号、状态机和登记册一期基础','规划使用日志、场景识别、成本与风险洞察的后续治理链'],evidence:'完成项目章程与一期登记闸门基础，覆盖约 31 个存量项目的治理视角。',boundary:'当前完成的是一期基础；使用埋点、成本分析与风险洞察属于后续目标，不表述为已上线能力。',image:'assets/previews/ai-platform.webp'},
{id:'buyflow',title:'行政采购协同平台',type:'AI-ASSISTED / 采购协同',category:'ai-assisted',status:'高完成度 Demo',proof:'多门店提单 → 智能拆单 → 履约',summary:'统一采购入口，用 AI 辅助处理多门店、仓库与供应商混合拆单。',problem:'大批量行政采购同时涉及多个门店、上千商品与不同履约来源，人工归类容易遗漏且难追溯。',work:['统一商品选择与批量上传入口','设计 AI 拆单、运行日志和人工复核','覆盖审批、履约、签收和追溯'],evidence:'代码覆盖主要交互与白盒运行演示。',boundary:'商品、模型运行与履约数据均为模拟，不能写成已上线成果。',image:'assets/previews/buyflow.webp'},
{id:'dictionary',title:'数据字典准确性与消歧',type:'AI GOVERNANCE / 数据语义',category:'ai-governance',status:'诊断与测试完成',proof:'L0 / L1 / L2 三层诊断',summary:'在自然语言查数的准确率、口径治理与交互成本之间建立分层处理。',problem:'自然语言可能选错指标或静默默认错误口径。',work:['量化关键词冲突','设计按风险分层的澄清策略','用对抗测试校正理论规则'],evidence:'完成问题分层、方案和对抗测试。',boundary:'部分方向仍待真实用户查询验证。',image:'assets/previews/dictionary.webp'}
];

const categoryMeta={
 'business-system':{label:'BUSINESS SYSTEM',accent:'var(--orange)',logic:'03 / SYSTEM LOGIC'},
 'ai-assisted':{label:'AI-ASSISTED SYSTEM',accent:'var(--lime)',logic:'03 / AI WORKFLOW'},
 'ai-workflow':{label:'AI WORKFLOW',accent:'var(--violet)',logic:'03 / AI WORKFLOW'},
 'ai-governance':{label:'AI GOVERNANCE',accent:'var(--blue)',logic:'03 / AI GOVERNANCE'}
};

const caseDetails={
permission:{thesis:'让自然语言查数进入可信边界：AI 理解问题，系统决定权限，结果返回前再次校验并留痕。',role:'业务规则梳理、权限模型、执行闸门、真实身份联调与红队测试。',maturity:'已投入使用 1 个月；初期采用偏严格的权限策略，上线后根据真实反馈调整了约 5 个字段权限，目前日常使用正常。',context:'公司员工可以通过自然语言查询业务数据，但岗位、品牌、门店与区域之间存在复杂的数据边界。',users:'买手、店员、区域与职能岗位，以及维护 AI 查数链路的数据和技术团队。',solution:'以 RBAC 管理角色到字段组，以 ABAC 约束品牌、门店、区域、仓库和本人范围，把策略放进查询执行前，并在结果返回前检查敏感字段和输出范围。',features:['73 类真实系统角色映射','416 个字段的原始/加工属性与敏感度分级','默认拒绝、查询前早拦与敏感字段扫描','输出范围校验与查询审计','上线后完成首轮约 5 个字段权限校准'],aiTitle:'AI 可以理解问题，但不能决定权限。',aiNote:'自然语言模型负责理解查询意图；真实身份、字段权限、数据范围与输出校验由确定性策略执行。即使提示词被绕过，底层查询和最终输出仍必须被拦截。',aiSplit:[['AI','理解用户问题并选择受控指标'],['RULES','校验身份、权限、查询与输出范围'],['HUMAN','确认多角色敏感权限与例外']],decisions:['RBAC 管字段可见性，ABAC 管数据范围','动态解析真实身份，静态名单只作为降级路径','一个指标对应一条受控查询，降低自由 SQL 绕过空间'],process:['用户提出自然语言问题','系统识别真实身份与角色','查询前校验字段和数据范围','执行受控查询并生成结果','返回前校验敏感字段与输出范围','返回结果并记录审计日志'],next:'持续记录拦截与放行情况，并在新增角色、字段或业务场景时复核权限边界。'},
ctc:{thesis:'把依赖多人经验的调拨判断，变成可配置、可比较、可回滚的确定性计算系统。',role:'独立负责业务逻辑、算法、数据接入、网页产品、测试与持续迭代。',maturity:'完成个人调试、团队试用和多轮人工方案对比。',context:'调拨需要同时判断门店需求、库存、在途、销售速度、商品阶段、尺码和总量约束，人工表格难以稳定复现。',users:'商品运营、调拨执行人员与需要复核调拨建议的业务负责人。',solution:'系统把预测库存、需求池、门店优先级、尺码结构和业务模式串进同一分配链，并保留审批、运行记录和撤销能力。',features:['区分快慢销、新品、成熟品和退市品的商品预测','考虑 lead time 与到货前销售的 Projected Stock','门店优先级、明确需求和尺码保底','买断、代销、自生产等可配置约束','新旧算法双轨、运行审计与回滚'],aiTitle:'核心是可解释、可复核的业务算法。',aiNote:'预测与分配来自确定性代码、业务公式和场景参数。每个建议都能追溯输入、约束与计算版本，人工复核后才进入正式下单。',aiSplit:[['CODE','计算预测库存、需求池与分配结果'],['RULES','控制库存、尺码、门店与模式约束'],['HUMAN','复核建议、处理换季场景并正式下单']],decisions:['Projected Stock 必须考虑到货前销售与 lead time','常规补货与换季首铺拆成不同业务场景','不用单一准确率掩盖不同阶段和不同场景的差异'],process:['从单品牌脚本验证方向','扩展为网页工具与多品牌跑批','个人持续调试约一个月','团队试用并与人工调拨对比','按场景校正预测和分配逻辑'],next:'记录人工复核时间、建议采用比例，以及调拨后销售、缺货和库存变化。'},
otb:{thesis:'让预算、采购、销售、毛利、库存与调整审批在同一决策界面里对齐。',role:'指标口径治理、真实数据接入、下钻结构、筛选与版本记录设计。',maturity:'真实数据接入并已部署，用于辅助买手与企划跟踪买货节奏。',context:'OTB 计划、预算、订单和销售分散在不同表格与系统，品牌与筛选口径不一致，偏差经常到复盘时才被发现。',users:'买手、商品企划和负责预算、毛利与库存管理的业务人员。',solution:'把计划、实际和目标放在同一产品中，从采购组下钻到品牌，并将发现偏差继续连接到预算调整和审批记录。',features:['OTB、采购、销售、毛利和库存同屏对照','采购组到品牌下钻与多维筛选','Excel 上传、解析与版本记录','交通灯提示、预算调整与分级审批','约 21 个看板接口接入真实经营数据'],aiTitle:'价值来自可信口径、真实数据与可追溯决策。',aiNote:'指标、筛选、偏差和审批均由确定性查询与状态规则执行。系统展示事实与影响，预算责任和买货判断仍由业务人员承担。',aiSplit:[['DATA','提供统一、可下钻的经营事实'],['CODE','按确定性口径识别偏差并记录版本'],['HUMAN','决定预算、采购与买货节奏']],decisions:['先统一指标口径，再增加页面能力','筛选范围必须同时约束分子与分母','门店库存必须排除仓库，避免成本和周转虚高'],process:['梳理分散数据与业务口径','逐项对数并修复严重错误','接入计划、目标与真实查询','设计下钻、上传和调整审批','部署为买货辅助工具'],next:'记录使用频率、被采纳动作、影响金额与版本调整结果。'},
'old-stock':{thesis:'把一次性盘点表变成业务人员可以持续查询、跟进并采取动作的经营工具。',role:'业务问题拆解、信息结构、查询界面和真实使用迭代。',maturity:'已有真实业务人员使用，并形成明确的处理周期变化。',context:'老货识别依赖分散数据与人工判断，库龄、库存、销售状态和后续动作难以在同一处查看。',users:'商品运营以及负责清货、调拨、降价和库存跟进的业务人员。',solution:'将老货识别和商品明细转成可查询工具，让业务人员从发现老货继续走到经营动作，而不是重复传递静态表格。',features:['库龄、库存与销售状态统一查询','从汇总继续下钻到商品明细','为清货、调拨、降价和观察提供工作入口','可重复使用，而非一次性盘点文件'],aiTitle:'先把查询、判断依据和经营跟进做稳定。',aiNote:'老货识别、筛选和状态均由确定性数据规则执行。系统负责把事实组织清楚，商品人员根据库存和经营目标决定清货、调拨或继续观察。',aiSplit:[['DATA','识别老货并呈现经营状态'],['CODE','执行查询、筛选与状态跟进'],['HUMAN','选择清货、调拨或观察动作']],decisions:['同时呈现库龄、库存、销售状态和后续动作','让明细可被直接查询，而不是继续传递表格','效率结果与后续经营结果分开衡量'],process:['还原人工盘点过程','整合老货识别与商品明细','形成查询和跟进工具','交付业务人员使用','记录处理周期变化'],next:'补齐实际使用人数、覆盖商品，以及后续经营动作和库存结果。'},
catalog:{thesis:'把商品图片、属性和到货信息放进同一个可筛选视图，降低跨部门信息壁垒。',role:'商品信息架构、筛选维度、卡片视图与后续生命周期连接规划。',maturity:'已形成真实页面；使用规模和刷新机制仍待记录。',context:'每季新商品数量大，图片和属性分散，非直接经手人员很难快速知道有哪些款、长什么样以及何时到货。',users:'企划、运营、门店、市场及需要快速了解当季商品的协作角色。',solution:'把商品视觉信息与结构化属性放在同一目录，通过品牌、分类、季节、性别和到货日期等条件快速检索。',features:['商品图片、SPU、货号与价格卡片','品牌、季节、性别、颜色和尺码属性','采购组与一至三级分类筛选','到货量和首次到货日期查询'],aiTitle:'重点是完整、准确、稳定的商品视图。',aiNote:'目录通过确定性字段、筛选条件和查询接口组织商品事实。当前价值是让协作角色快速找到正确商品，而不是增加无法验证的智能推荐。',aiSplit:[['DATA','统一图片、属性与到货信息'],['CODE','执行多维筛选与商品检索'],['HUMAN','基于商品事实开展企划与协作']],decisions:['视觉信息和结构化属性必须在同一界面','筛选围绕真实工作任务，而不是堆叠字段','为经营表现和生命周期连接预留结构'],process:['梳理跨部门查商品任务','统一图片与关键属性','设计筛选和卡片视图','形成真实页面','规划生命周期连接'],next:'记录覆盖 SPU、刷新频率、活跃用户与典型使用任务。'},
'gap-radar':{thesis:'先用透明计算找到缺口，再让 AI 把证据整理成可审阅、可追踪的企划机会假设。',role:'机会结构、透明计算、数据质量校验，以及 AI 证据解释与人工确认工作流设计。',maturity:'确定性缺口计算已完成真实数据验证；AI Workflow 为下一阶段产品方案，尚未上线。',context:'企划判断容易依赖经验，外部市场数据又难取得且口径不一；内部不同品牌组已经形成可比较的自然样本。',users:'商品企划、买手及需要判断品类、价格带和商品结构机会的业务人员。',solution:'系统先以三级品类、价格带和品牌组计算结构缺口，再由 AI 读取受控证据，生成原因解释、缺失信息与机会假设，最后交给企划人员确认是否进入 Brief。',features:['确定性四类缺口结构与透明机会金额','3 个半年度、5 个品牌组的数据覆盖','AI 输出绑定来源、数据时间与缺失项','High / Medium / Low 置信分级，不显示伪精确百分比','企划人员可接受、编辑或驳回机会假设'],aiTitle:'AI 负责解释证据，不负责创造需求事实。',aiNote:'经营数据和规则先产生候选缺口；AI 只读取与当前品类相关的证据，输出原因、风险、缺失信息和机会假设。数据缺失或来源冲突时降级为低置信并停止进入企划 Brief。',aiSplit:[['CODE','计算缺口、机会金额与数据质量状态'],['AI','解释证据，生成原因与机会假设'],['HUMAN','确认、修改或驳回，并决定是否进入企划']],decisions:['AI 不得修改确定性缺口值和机会金额','每条解释必须带来源、数据时间和最弱证据','只有人工确认的机会才能进入企划 Brief'],process:['已完成 · 统一口径并计算结构缺口','已完成 · 跨周期和品牌组验证结果','下一阶段 · AI 读取证据并生成机会假设','下一阶段 · 企划确认、修改或驳回','下一阶段 · 进入 Brief 并追踪买货与经营结果'],next:'先用历史已知案例评估解释准确性与企划编辑量，再小范围上线 AI 节点并持续记录采用率和经营结果。'},
'career-agent':{thesis:'让 AI 主动发现和理解机会，但把职业判断与对外沟通权留在用户手里。',role:'产品定位、工作流设计、前后端实现、LLM 编排、浏览器自动化、人审与日志设计。',maturity:'代码覆盖完整本地流程；依赖招聘平台页面和登录状态，尚未形成公开生产服务。',context:'求职者需要反复搜索多个平台、阅读长 JD、比较匹配程度并逐个编写沟通话术，重复劳动占据了真正用于职业判断的时间。',users:'希望系统化管理求职机会、但仍要亲自决定是否沟通和投递的求职者。',solution:'系统基于职业画像搜索并采集岗位，用 LLM 完成 JD 结构化、匹配评分与话术草稿，用户确认后才调用浏览器执行，并记录每一步结果。',features:['智联与 BOSS 的真实浏览器采集和截图','JD 结构化、匹配评分、证据与风险提示','模型不可用时启用透明的启发式评分','可编辑沟通草稿与发送前人工确认','模型、输入输出、耗时、工具与人工决策日志'],aiTitle:'AI 缩短发现与判断循环，不替用户做职业决定。',aiNote:'AI 处理非结构化 JD、匹配分析与沟通草稿；确定性代码控制状态、互斥、回退和日志；任何对外沟通都必须由用户看过岗位、依据和话术后确认。',aiSplit:[['WORKFLOW','编排采集、分析、确认、执行与留证'],['AI','理解 JD、评分并生成可编辑话术'],['HUMAN','决定机会是否值得投入并批准对外沟通']],decisions:['发送消息必须人工确认，不做无人值守批量投递','异常情况下回退到透明的确定性评分','日志记录决策变量和工具事件，不暴露隐藏推理'],process:['配置职业画像与搜索条件','浏览器采集岗位和完整 JD','AI 结构化、评分并生成话术','用户查看证据、编辑并确认','浏览器执行沟通并截图留证'],next:'用代表性岗位评测推荐准确性、接受率、沟通草稿编辑量、人工判断时间、沟通转化与平台执行成功率。'},
hive:{thesis:'先让企业 AI 有入口、有责任和可追踪状态，再把真实使用、成本与风险变成治理依据。',role:'提出治理逻辑，设计六阶段框架，并完成本人版本的一期登记闸门基础。',maturity:'本人版本完成一期登记闸门；使用透明、成本记录和风险洞察是后续治理目标，尚未全部落地。',context:'约 31 个内部 AI 项目分散推进时，仅看 Demo 或项目清单，管理者无法持续判断谁在使用、用于什么场景、投入是否合理，以及应该继续还是退出。',users:'AI 项目发起人、部门负责人、技术支持与需要掌握 AI 使用健康度的管理者。',solution:'一期用登记号、负责人和状态机建立准入闸门；完整方案再连接身份、AI 调用日志、模型与成本记录，由 AI 聚合场景和异常，管理者据此作资源决策。',features:['六阶段 AI 项目治理框架','登记字段、登记号与状态机','项目登记册、身份登录与移动端基础','使用者、模型、时间、成本和场景的后续日志设计','AI 场景归类、异常提示与管理洞察的后续方案'],aiTitle:'AI 帮助识别模式，治理决定必须保留证据和责任人。',aiNote:'系统负责身份、权限、流程、成本记录与审计；AI 只对受控日志做场景归类、趋势解释和风险提示。资源投入、风险处置和项目退出仍由管理者基于证据决定。',aiSplit:[['SYSTEM','记录身份、模型、时间、成本与流程状态'],['AI','归类使用场景、识别异常并生成管理摘要'],['HUMAN','决定资源、整改、继续投入或退出']],decisions:['一期先解决入口、责任人与状态，不虚构完整使用洞察','AI 洞察必须能回到原始日志与统计口径','成本、风险与项目退出属于管理决策，不由模型自动执行'],process:['形成项目章程与六阶段路线图','完成登记表单、登记号和状态机','建立负责人、项目与状态的基础记录','后续连接使用、模型与成本日志','后续由 AI 归类场景并提示异常','管理者复核证据并作治理决策'],next:'正式资源到位后，再分阶段验证使用埋点、成本口径、场景归类准确性和管理者采纳情况。'},
buyflow:{thesis:'让所有行政采购进入同一张采购单，再用可审计的 AI 工作流辅助复杂拆单。',role:'统一提单、批量数据入口、AI 拆单控制、人工复核、履约追溯与运行日志设计。',maturity:'高完成度 Demo；商品、模型运行和履约数据均为模拟，尚未真实上线。',context:'行政采购可能一次提交多个门店、上千件商品，并同时涉及仓库发货、供应商采购和同品混合履约。',users:'行政申请人、采购执行、审批人、仓库、供应商与门店签收人员。',solution:'员工从统一采购单选择商品或批量上传；系统完成字段校验后，AI 结合仓库库存、供应商目录、交期和配送限制生成拆单建议，人工复核后才进入审批与下发。',features:['统一商品选择与批量上传入口','多门店与上千行明细校验','仓库和供应商混合履约建议','模型、Prompt、输入来源与逐次 Run ID 日志','低置信异常转人工，保留建议版与最终版','审批后生成履约单并持续追溯'],aiTitle:'AI 处理复杂归类，规则守住数量与执行边界。',aiNote:'LLM 用于理解商品描述、组合候选来源和归纳异常；金额、库存扣减、数量守恒、权限与审批由确定性规则控制。界面展示判断变量和依据，不暴露隐藏思维过程。',aiSplit:[['AI','商品语义归类、混合履约建议与异常摘要'],['RULES','字段校验、库存锁定、数量守恒与执行权限'],['HUMAN','复核低置信项并批准真实下发']],decisions:['所有人使用同一套采购单，不另建 AI 提单入口','每次分析保留输入快照、模型与 Prompt 版本、依据和人工修改','低置信、运费未知和配送冲突必须转人工'],process:['选择商品或批量上传','校验门店、商品与需求字段','运行并记录拆单分析','人工处理异常和确认归属','审批后生成仓库与供应商履约单'],next:'用真实历史采购单评测拆单准确性、人工修改率、复核耗时与异常漏检。'},
dictionary:{thesis:'把 AI 查数不准拆成复合需求、词条选择和口径对齐三层，而不是只靠增加反问。',role:'错误链路诊断、冲突扫描、澄清策略、对抗测试和产品取舍。',maturity:'完成诊断、方案与对抗测试；部分规则仍待真实用户查询校准。',context:'用户用自然语言查数时，一个词可能命中多个指标；即使指标正确，时间、退货和粒度口径也可能被静默默认。',users:'使用自然语言查询经营数据的业务人员，以及维护数据字典和查数体验的团队。',solution:'把错误链路拆成 L0 复合需求、L1 词条选择和 L2 口径对齐，并按风险决定直接回答、默认声明或发起确认。',features:['指标索引与关键词冲突扫描','真实歧义与噪音分层','低打扰的澄清策略','对抗测试与规则修正','面向真实查询的回归评测方向'],aiTitle:'准确率和交互成本需要一起设计。',aiNote:'每次都反问会让系统安全却难用；从不确认又会静默出错。AI 负责理解语言，数据字典提供标准指标，产品策略根据风险决定何时打断。',aiSplit:[['AI','理解复合需求与用户表达'],['DICTIONARY','提供标准指标、口径和受控查询'],['UX POLICY','按风险决定默认、声明或确认']],decisions:['够具体则不打断，模糊时默认并声明，高风险才确认','理论关键词冲突必须用真实查询校准','数据权限不能寄托在提示词层'],process:['扫描指标与触发词','划分三层错误链路','设计分层澄清策略','执行对抗测试','转向真实查询评测'],next:'收集真实用户查询，建立可回归评测集并量化准确率与体验权衡。'}
};

const steps=[
{title:'先看任务如何发生',body:'理解谁在参与、信息在哪里流失。不要把一句“效率低”直接翻译成功能需求。',image:'assets/previews/step-field.webp'},
{title:'把症状、原因和结果分开',body:'明确目标、口径、角色和约束。哪些是流程问题，哪些是数据问题，哪些才需要 AI。',image:'assets/previews/step-define.webp'},
{title:'让经验变成可执行规则',body:'把隐性判断写成流程、状态、指标、例外与回滚机制，让系统能够解释结果。',image:'assets/previews/step-model.webp'},
{title:'连接数据、权限与业务动作',body:'界面不是终点。产品需要进入真实链路，让用户能发现问题并采取下一步动作。',image:'assets/previews/step-product.webp'},
{title:'用真实结果校正系统',body:'与人工答案、历史数据或实际用户对照，记录采用、删改、异常和最终经营结果。',image:'assets/previews/step-validate.webp'}
];
function renderStep(i){const s=steps[i];document.querySelector('#stepPanel').innerHTML=`<div><p class="label">STEP ${String(i+1).padStart(2,'0')}</p><h3>${s.title}</h3><p>${s.body}</p></div><div class="step-image"><img src="${s.image}" loading="lazy" decoding="async" alt="该阶段的脱敏项目界面"></div>`}

const questions=[
{q:'提示词能承担数据权限吗？',a:'不能。',text:'提示词可以解释规则，但重要权限必须进入身份、策略和查询执行链。'},
{q:'算法达到 85%，就能替代人工吗？',a:'不能直接推导。',text:'准确性随场景变化，人工复核与经营结果也必须记录。'},
{q:'做出 Demo，等于创造价值吗？',a:'不等于。',text:'Demo 证明能做，真实采用证明有用，经营结果才能证明改变。'}
];
function renderQuestions(){document.querySelector('#questionList').innerHTML=questions.map((q,i)=>`<article class="question"><span class="label">QUESTION ${String(i+1).padStart(2,'0')}</span><h3>${q.q}</h3><button data-question>Reveal my answer</button><div class="question-answer"><b>${q.a}</b><p>${q.text}</p><button data-question>Close</button></div></article>`).join('')}

let filter='all',activeIndex=0,lastFocus=null,reelIndex=0,archiveList=projects,reelFrame=0,reelSuppressClick=false,reelSettleTimer=0;
function visualMarkup(p,i,label){if(p.image)return `<img src="${p.image}" loading="lazy" decoding="async" alt="${p.title}经过脱敏处理的界面预览">`;if(p.id==='career-agent')return `<span class="workflow-cover"><em>DISCOVER</em><i>→</i><em>ANALYZE</em><i>→</i><em>REVIEW</em><i>→</i><em>ACT</em></span><b>${label}<br>${String(i+1).padStart(2,'0')}</b>`;return `<span>${categoryMeta[p.category]?.label||p.type.split(' / ')[0]}</span><b>${label}<br>${String(i+1).padStart(2,'0')}</b>`}
function renderArchive(){
 archiveList=projects.filter(p=>filter==='all'||p.category===filter);reelIndex=0;
 document.querySelector('#archiveCounter').textContent=`${String(archiveList.length).padStart(2,'0')} PROJECTS`;
 const reelItems=archiveList.length>1?[{project:archiveList.at(-1),index:archiveList.length-1,clone:'last'},...archiveList.map((project,index)=>({project,index,clone:''})),{project:archiveList[0],index:0,clone:'first'}]:archiveList.map((project,index)=>({project,index,clone:''}));
 document.querySelector('#reelGrid').innerHTML=reelItems.map(({project:p,index:i,clone})=>`<article class="reel-card category-${p.category} ${!clone&&i===0?'active':''}" tabindex="${clone?'-1':'0'}" role="button" data-reel-index="${i}" ${clone?`data-reel-clone="${clone}" aria-hidden="true"`:''} data-open="${p.id}" style="--reel-accent:${categoryMeta[p.category]?.accent||'var(--orange)'}"><span class="reel-media ${p.image?'':'typographic'}">${visualMarkup(p,i,'PROJECT')}</span><span class="reel-overlay"><span>${String(i+1).padStart(2,'0')} / ${categoryMeta[p.category]?.label||p.status}</span><strong>${p.title}</strong><p>${p.summary}</p><b>${p.proof}</b><small>${p.status}</small></span></article>`).join('');
 requestAnimationFrame(()=>{const cards=[...document.querySelectorAll('#reelGrid .reel-card')],first=cards.find(card=>!card.dataset.reelClone&&card.dataset.reelIndex==='0');scrollReelCard(first,'auto');syncReel()})
}
function scrollReelCard(card,behavior='smooth'){if(!card)return;const track=document.querySelector('#reelGrid');track.scrollTo({left:card.offsetLeft-(track.clientWidth-card.offsetWidth)/2,behavior})}
function syncReel(){const track=document.querySelector('#reelGrid'),cards=[...track.querySelectorAll('.reel-card')];if(!cards.length)return;const center=track.scrollLeft+track.clientWidth/2;let nearest=0,distance=Infinity;cards.forEach((card,i)=>{const cardCenter=card.offsetLeft+card.offsetWidth/2,d=cardCenter-center,span=card.offsetWidth+parseFloat(getComputedStyle(track).gap||0),offset=Math.max(-2.2,Math.min(2.2,d/span));card.style.setProperty('--reel-offset',offset.toFixed(3));card.style.setProperty('--reel-abs',Math.abs(offset).toFixed(3));card.style.zIndex=String(20-Math.round(Math.abs(offset)*5));if(Math.abs(d)<distance){distance=Math.abs(d);nearest=i}});const activeCard=cards[nearest],realIndex=Number(activeCard.dataset.reelIndex);reelIndex=realIndex;cards.forEach((card,i)=>card.classList.toggle('active',i===nearest));const count=`${String(realIndex+1).padStart(2,'0')} / ${String(archiveList.length).padStart(2,'0')}`;document.querySelector('#reelCount').textContent=count;document.querySelector('#archiveCounter').textContent=count;document.querySelector('#reelProgress').style.transform=`scaleX(${(realIndex+1)/archiveList.length})`;clearTimeout(reelSettleTimer);reelSettleTimer=setTimeout(()=>{if(track.classList.contains('dragging')||!activeCard.dataset.reelClone)return;const target=cards.find(card=>!card.dataset.reelClone&&card.dataset.reelIndex===activeCard.dataset.reelIndex);scrollReelCard(target,'auto')},140)}
function text(id,value){document.querySelector(id).textContent=value}
const interactiveDemos={permission:{src:'demos/permission.html?v=22',path:'demo.local/permission/check'},ctc:{src:'demos/ctc-bundle.html?v=22',path:'demo.local/ctc/run'},otb:{src:'demos/otb-bundle.html?v=18',path:'demo.local/otb/overview'},'gap-radar':{src:'demos/gap-radar-bundle.html?v=22',path:'demo.local/assortment/opportunities'},'career-agent':{src:'demos/career-agent.html?v=1',path:'demo.local/career-agent/workflow'},buyflow:{src:'demos/buyflow.html?v=22',path:'demo.local/buyflow/purchase/new'}};
function caseVisual(p,i){const demo=interactiveDemos[p.id];if(demo)return `<div class="demo-browser"><div class="browser-tabs"><span class="browser-dots"><i></i><i></i><i></i></span><span class="browser-tab">${p.title}<b>×</b></span><button data-demo-action="reload" aria-label="重置 Demo">↻</button></div><div class="browser-bar"><span>‹</span><span>›</span><button data-demo-action="reload" aria-label="刷新 Demo">↻</button><div><i>◆</i>${demo.path}</div><button data-demo-action="open" data-demo-src="${demo.src}">全屏打开 ↗</button></div><div class="browser-note"><b>INTERACTIVE DEMO</b><span>全部为虚构数据，可直接操作</span></div><div class="demo-loading"><i></i><b>正在加载交互 Demo</b><span>首次打开需要片刻</span><button data-demo-action="open" data-demo-src="${demo.src}">直接打开 ↗</button></div><iframe src="${demo.src}" title="${p.title}交互演示" loading="eager" onload="const browser=this.closest('.demo-browser');browser.classList.add('demo-ready');browser.querySelector('.demo-loading')?.remove()"></iframe></div>`;if(p.image)return `<img src="${p.image}" loading="eager" decoding="async" alt="${p.title}界面节选"><figcaption>PRODUCT INTERFACE / SELECTED VIEW</figcaption>`;const workflow=p.id==='career-agent'?'<div class="case-workflow"><span>DISCOVER</span><i>→</i><span>ANALYZE</span><i>→</i><span>REVIEW</span><i>→</i><span>ACT</span></div>':'';return `<div class="case-type-cover ${p.id==='career-agent'?'career-agent-cover':''}" style="--case-accent:${categoryMeta[p.category]?.accent||'var(--orange)'}"><span>${categoryMeta[p.category]?.label||p.type}</span>${workflow}<b>CASE<br>${String(i+1).padStart(2,'0')}</b><small>${p.status}</small></div>`}
function list(id,items){document.querySelector(id).innerHTML=items.map(x=>`<li>${x}</li>`).join('')}
function openDetail(id,source,updateRoute=true){const i=projects.findIndex(p=>p.id===id);if(i<0)return;activeIndex=i;lastFocus=source||lastFocus;const p=projects[i],d=caseDetails[id],next=projects[(i+1)%projects.length];text('#detailCount',`${String(i+1).padStart(2,'0')} / ${projects.length}`);text('#detailType',p.type);text('#detailTitle',p.title);text('#detailSummary',p.summary);text('#detailStatus',p.status);text('#detailProof',p.proof);text('#detailProofLarge',p.proof);text('#detailProblem',p.problem);text('#detailEvidence',p.evidence);text('#detailBoundary',p.boundary);text('#detailThesis',d.thesis);text('#detailRole',d.role);text('#detailMaturity',d.maturity);text('#detailContext',d.context);text('#detailUsers',d.users);text('#detailSolution',d.solution);text('#detailLogicLabel',categoryMeta[p.category]?.logic||'03 / SYSTEM LOGIC');text('#detailAiTitle',d.aiTitle);text('#detailAiNote',d.aiNote);text('#detailNextStep',d.next);text('#detailNextTitle',next.title);list('#detailFeatures',d.features);list('#detailWork',p.work);list('#detailDecisions',d.decisions);list('#detailProcess',d.process);document.querySelector('#detailAiSplit').innerHTML=d.aiSplit.map(([label,body])=>`<div><span>${label}</span><p>${body}</p></div>`).join('');document.querySelector('#detailVisual').innerHTML=caseVisual(p,i);document.querySelector('#detailNextCase').dataset.next=next.id;const detail=document.querySelector('#detail');detail.classList.add('open');detail.setAttribute('aria-hidden','false');detail.scrollTop=0;document.body.style.overflow='hidden';if(updateRoute&&location.hash!==`#case=${id}`)history.pushState({case:id},'',`#case=${id}`)}
function closeDetail(updateRoute=true){const detail=document.querySelector('#detail');detail.classList.remove('open');detail.setAttribute('aria-hidden','true');document.body.style.overflow='';if(updateRoute&&location.hash.startsWith('#case='))history.replaceState({},'',location.pathname+location.search);setTimeout(()=>lastFocus?.focus(),50)}
function syncCaseRoute(){const match=location.hash.match(/^#case=([\w-]+)$/);if(match&&projects.some(p=>p.id===match[1]))openDetail(match[1],null,false);else if(document.querySelector('#detail').classList.contains('open'))closeDetail(false)}

document.addEventListener('click',e=>{
 const demoAction=e.target.closest('[data-demo-action]');if(demoAction){const browser=demoAction.closest('.demo-browser'),frame=browser?.querySelector('iframe');if(demoAction.dataset.demoAction==='reload'&&frame)frame.src=frame.src;if(demoAction.dataset.demoAction==='open')window.open(demoAction.dataset.demoSrc,'_blank','noopener');return}
 const step=e.target.closest('[data-step]');if(step){document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',x===step));renderStep(Number(step.dataset.step))}
 const question=e.target.closest('[data-question]');if(question)question.closest('.question').classList.toggle('open');
 const impact=e.target.closest('.impact-card');if(impact&&!e.target.closest('[data-open]'))activateInGroup('.impact-card',impact);
 const strength=e.target.closest('.strength-rail');if(strength){document.querySelectorAll('.strength-rail').forEach(x=>x.classList.toggle('active',x===strength))}
 const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===f));renderArchive()}
 const reel=e.target.closest('[data-reel-index]');if(reel&&reelSuppressClick){reelSuppressClick=false;return}
 const open=e.target.closest('[data-open]');if(open)openDetail(open.dataset.open,open);
});
document.querySelector('#detailClose').addEventListener('click',()=>closeDetail());document.querySelector('#detailPrev').addEventListener('click',()=>openDetail(projects[(activeIndex-1+projects.length)%projects.length].id));document.querySelector('#detailNext').addEventListener('click',()=>openDetail(projects[(activeIndex+1)%projects.length].id));document.querySelector('#detailNextCase').addEventListener('click',e=>openDetail(e.currentTarget.dataset.next));window.addEventListener('popstate',syncCaseRoute);window.addEventListener('hashchange',syncCaseRoute);
function activateInGroup(selector,target){document.querySelectorAll(selector).forEach(x=>x.classList.toggle('active',x===target))}
document.querySelectorAll('.impact-card').forEach(card=>{card.addEventListener('pointerenter',()=>activateInGroup('.impact-card',card));card.addEventListener('focusin',()=>activateInGroup('.impact-card',card))});
document.querySelectorAll('.strength-rail').forEach(rail=>{rail.addEventListener('pointerenter',()=>activateInGroup('.strength-rail',rail));rail.addEventListener('focusin',()=>activateInGroup('.strength-rail',rail))});

const reelGrid=document.querySelector('#reelGrid');let reelDrag=null;
function endReelDrag(e){if(!reelDrag)return;const moved=reelDrag.moved,pointerId=reelDrag.pointerId;if(reelGrid.hasPointerCapture(pointerId))reelGrid.releasePointerCapture(pointerId);reelDrag=null;reelGrid.classList.remove('dragging');if(moved)setTimeout(()=>{reelSuppressClick=false},0)}
reelGrid.addEventListener('scroll',()=>{cancelAnimationFrame(reelFrame);reelFrame=requestAnimationFrame(syncReel)});
reelGrid.addEventListener('pointerdown',e=>{if(e.button!==0&&!['touch','pen'].includes(e.pointerType))return;const card=e.target.closest('.reel-card');if(!card)return;reelDrag={x:e.clientX,scroll:reelGrid.scrollLeft,pointerId:e.pointerId,moved:false}});
reelGrid.addEventListener('pointermove',e=>{if(!reelDrag||e.pointerId!==reelDrag.pointerId)return;const dx=e.clientX-reelDrag.x;if(!reelDrag.moved&&Math.abs(dx)>6){reelDrag.moved=true;reelSuppressClick=true;reelGrid.classList.add('dragging');reelGrid.setPointerCapture(e.pointerId)}if(reelDrag.moved)reelGrid.scrollLeft=reelDrag.scroll-dx});
reelGrid.addEventListener('pointerup',endReelDrag);reelGrid.addEventListener('pointercancel',endReelDrag);
reelGrid.addEventListener('keydown',e=>{const card=e.target.closest('.reel-card:not([data-reel-clone])');if(card&&['Enter',' '].includes(e.key)){e.preventDefault();openDetail(card.dataset.open,card);return}if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const cards=[...reelGrid.querySelectorAll('.reel-card:not([data-reel-clone])')],current=Math.max(0,cards.indexOf(document.activeElement)),next=Math.max(0,Math.min(cards.length-1,current+(e.key==='ArrowRight'?1:-1)));scrollReelCard(cards[next]);cards[next].focus({preventScroll:true})});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('#detail').classList.contains('open'))closeDetail()});document.querySelector('#themeToggle').addEventListener('click',()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark');
renderStep(0);renderQuestions();renderArchive();syncCaseRoute();
