const projects=[
{id:'permission',title:'数据权限治理系统',type:'AI治理 / 数据产品',category:'governance',status:'已投入使用 · 运行 1 个月',proof:'73 类角色 / 416 个字段 / 首轮约 5 个字段校准',summary:'把业务权限从提示词约束，变成查询执行前可拦截、可审计的系统控制。',problem:'自然语言查数链路缺少稳定的字段级和行级权限。身份丢失、多角色叠加与自由 SQL 都可能造成越权。',work:['梳理岗位、字段敏感度与可见范围','设计 RBAC、ABAC、默认拒绝和查询前早拦','联调真实身份与查询链路，进行越权与绕过测试'],evidence:'完成 73 类真实系统角色映射与 416 个字段分级；系统投入使用后，根据真实反馈完成首轮约 5 个字段的权限校准。',boundary:'已投入使用 1 个月，并完成首轮权限校准。目前日常使用正常，整体反馈良好。',image:'assets/previews/permission.webp'},
{id:'ctc',title:'CTC 调拨系统',type:'供应链 / 算法产品',category:'product',status:'真实试用',proof:'约 14 人天 → 约 30 分钟',summary:'把库存、在途、销售速度、门店需求和尺码约束，转化为可配置、可比较的调拨系统。',problem:'人工调拨依赖多人表格与经验，难以稳定复现，也缺少运行审计和效果对照。',work:['独立负责业务逻辑、算法、数据接入、网页产品与测试','建立商品预测、Projected Stock、需求池和尺码分配规则','保留新旧算法双轨、审批状态与回滚路径'],evidence:'个人调整约 1 个月后进入团队试用，主体计算约 30 分钟。',boundary:'不能宣称完全替代 14 人天，人工复核与正式下单仍需单独计算。',image:'assets/previews/ctc.webp'},
{id:'otb',title:'OTB 管理产品',type:'商品经营 / 数据产品',category:'product',status:'已部署使用',proof:'约 21 个真实查询接口',summary:'把预算、采购、销售、毛利、库存与调整审批放进同一决策界面。',problem:'计划、预算、订单和销售来自不同表格或系统，品牌口径不一致。',work:['统一关键指标口径并推动对数','支持采购组到品牌下钻、上传和版本记录','修复筛选分子错用全公司销售等严重口径问题'],evidence:'真实数据接入并部署，用于辅助买手买货。',boundary:'使用频率、被采纳动作和影响金额仍需持续记录。',image:'assets/previews/otb.webp'},
{id:'old-stock',title:'老货盘点系统',type:'商品运营产品',category:'product',status:'真实使用',proof:'约 2 周 → 3-4 天',summary:'把一次性盘点表转化为可查询、可跟进的老货经营工具。',problem:'业务人员难以同时看到库龄、库存、销售状态与后续动作。',work:['整合老货识别与商品明细','让业务人员直接查询并采取经营动作','把分散人工盘点转为可重复使用的工具'],evidence:'有真实业务人员使用，处理周期由约 2 周压缩到 3-4 天。',boundary:'实际使用人数、覆盖商品数和后续经营结果仍需补证。',image:'assets/previews/old-stock.webp'},
{id:'catalog',title:'商品目录',type:'企业信息产品',category:'product',status:'真实页面',proof:'图片、属性与到货统一检索',summary:'降低“只有直接经手人知道货长什么样”的信息壁垒。',problem:'商品图片和属性散落，跨部门查找与沟通成本高。',work:['整合商品图片与关键属性','设计多维筛选与统一商品视图','规划商品表现和生命周期连接'],evidence:'已形成真实页面。',boundary:'覆盖 SPU 数、刷新频率和活跃用户仍需补证。',image:'assets/previews/catalog.webp'},
{id:'gap-radar',title:'品类缺口雷达',type:'商品企划 / 决策产品',category:'research',status:'真实数据验证',proof:'3 个半年度 / 5 个品牌组',summary:'用内部多品牌自然样本，发现已经验证而本组覆盖不足的需求机会。',problem:'企划判断容易依赖经验，外部市场数据又难取得且口径不一。',work:['建立品类、价格带与品牌组的机会结构','设计透明的机会金额计算和周期刷新','完成总量、已知答案和复现检查'],evidence:'覆盖 3 个半年度和 5 个品牌组。',boundary:'机会是否进入买货及最终结果仍待跟踪。',image:'assets/previews/gap-radar.webp'},
{id:'defect',title:'残次标准与流程治理',type:'流程治理',category:'governance',status:'标准与培训完成',proof:'约 35 万条记录 / 数百条规则',summary:'先统一标准与责任，再讨论数字化。',problem:'多角色之间存在多套判定、申诉、退供与考核规则。',work:['梳理历史数据和规则','拆分可拍板项与待访谈项','推动标准确认和培训'],evidence:'推进到标准、流程和培训阶段。',boundary:'系统化后续未持续推进，不能写成完整上线闭环。'},
{id:'hive',title:'AI 项目管理平台',type:'AI 项目治理',category:'governance',status:'一期基础完成',proof:'约 31 个项目 / 六阶段治理',summary:'把准入、资源、代码、真实使用与催办串成连续治理链。',problem:'内部 AI 项目可能缺少入口、负责人、采用监控和退出机制。',work:['设计六阶段治理框架','完成登记号、状态机和登记册基础','明确本人版本和后续接手边界'],evidence:'完成项目章程与一期登记闸门基础。',boundary:'建群、代码监控和使用埋点未全部落地。',image:'assets/previews/ai-platform.webp'},
{id:'buyflow',title:'行政采购协同平台',type:'企业协同产品',category:'product',status:'高完成度 Demo',proof:'提单 → 发货 → 对账',summary:'用供应商 H5 和统一状态减少群聊追问与重复录入。',problem:'行政采购依赖群聊、纸质单据和反复沟通。',work:['设计端到端闭环','按供应商自动拆单','覆盖物流、签收和对账'],evidence:'代码覆盖主要模块。',boundary:'核心链路仍包含模拟数据，不能写成已上线成果。',image:'assets/previews/buyflow.webp'},
{id:'dictionary',title:'数据字典准确性与消歧',type:'AI 查数 / 数据语义',category:'governance',status:'诊断与测试完成',proof:'L0 / L1 / L2 三层诊断',summary:'在准确率与体验之间建立分层处理。',problem:'自然语言可能选错指标或静默默认错误口径。',work:['量化关键词冲突','设计按风险分层的澄清策略','用对抗测试校正理论规则'],evidence:'完成问题分层、方案和对抗测试。',boundary:'部分方向仍待真实用户查询验证。',image:'assets/previews/dictionary.webp'}
];

const caseDetails={
permission:{thesis:'把“谁能看什么”从提示词约束，推进到查询执行前可拦截、可审计的系统控制。',role:'业务规则梳理、权限模型、执行闸门、真实身份联调与红队测试。',maturity:'已投入使用 1 个月；初期采用偏严格的权限策略，上线后根据真实反馈调整了约 5 个字段权限，目前日常使用正常。',context:'公司员工可以通过自然语言查询业务数据，但岗位、品牌、门店与区域之间存在复杂的数据边界。',users:'买手、店员、区域与职能岗位，以及维护 AI 查数链路的数据和技术团队。',solution:'以 RBAC 管理角色到字段组，以 ABAC 约束品牌、门店、区域、仓库和本人范围，并把策略放进 SQL 执行前。',features:['73 类真实系统角色映射','416 个字段的原始/加工属性与敏感度分级','默认拒绝、查询前早拦与敏感字段扫描','上线后完成首轮约 5 个字段权限校准'],aiTitle:'AI 可以理解问题，但不能决定权限。',aiNote:'自然语言模型负责理解查询意图；真实身份、字段权限和数据范围由确定性策略执行。即使提示词被绕过，底层查询仍必须被拦截。',aiSplit:[['AI','理解用户问题并选择受控指标'],['RULES','解析身份、角色、字段和数据范围'],['HUMAN','确认多角色敏感权限与例外']],decisions:['RBAC 管字段可见性，ABAC 管数据范围','动态解析真实身份，静态名单只作为降级路径','一个指标对应一条受控查询，降低自由 SQL 绕过空间'],process:['梳理角色与数据边界','分级字段与数据范围','策略接入实际查询链','越权与绕过测试','上线并根据真实使用校准'],next:'持续记录拦截与放行情况，并在新增角色、字段或业务场景时复核权限边界。'},
ctc:{thesis:'把依赖多人经验的调拨判断，变成可配置、可比较、可回滚的计算系统。',role:'独立负责业务逻辑、算法、数据接入、网页产品、测试与持续迭代。',maturity:'完成个人调试、团队试用和多轮人工方案对比。',context:'调拨需要同时判断门店需求、库存、在途、销售速度、商品阶段、尺码和总量约束，人工表格难以稳定复现。',users:'商品运营、调拨执行人员与需要复核调拨建议的业务负责人。',solution:'系统把预测库存、需求池、门店优先级、尺码结构和业务模式串进同一分配链，并保留审批、运行记录和撤销能力。',features:['区分快慢销、新品、成熟品和退市品的商品预测','考虑 lead time 与到货前销售的 Projected Stock','门店优先级、明确需求和尺码保底','买断、代销、自生产等可配置约束','新旧算法双轨、运行审计与回滚'],aiTitle:'核心不是生成式 AI，而是可解释的业务算法。',aiNote:'预测和分配使用业务规则、数据计算与场景参数；AI 可辅助分析异常和解释结果，但不能跳过总量约束、尺码规则与人工下单确认。',aiSplit:[['MODEL','预测需求并生成调拨建议'],['RULES','控制库存、尺码、门店与模式约束'],['HUMAN','复核建议、处理换季场景并正式下单']],decisions:['Projected Stock 必须考虑到货前销售与 lead time','常规补货与换季首铺拆成不同业务场景','不用单一准确率掩盖不同阶段和不同场景的差异'],process:['从单品牌脚本验证方向','扩展为网页工具与多品牌跑批','个人持续调试约一个月','团队试用并与人工调拨对比','按场景校正预测和分配逻辑'],next:'记录人工复核时间、建议采用比例，以及调拨后销售、缺货和库存变化。'},
otb:{thesis:'让预算、采购、销售、毛利、库存与调整审批在同一决策界面里对齐。',role:'指标口径治理、真实数据接入、下钻结构、筛选与版本记录设计。',maturity:'真实数据接入并已部署，用于辅助买手与企划跟踪买货节奏。',context:'OTB 计划、预算、订单和销售分散在不同表格与系统，品牌与筛选口径不一致，偏差经常到复盘时才被发现。',users:'买手、商品企划和负责预算、毛利与库存管理的业务人员。',solution:'把计划、实际和目标放在同一产品中，从采购组下钻到品牌，并将发现偏差继续连接到预算调整和审批记录。',features:['OTB、采购、销售、毛利和库存同屏对照','采购组到品牌下钻与多维筛选','Excel 上传、解析与版本记录','交通灯提示、预算调整与分级审批','约 21 个看板接口接入真实经营数据'],aiTitle:'这里首先需要可靠数据，而不是 AI 生成答案。',aiNote:'页面的核心价值来自统一口径、真实查询和可追溯调整。AI 更适合辅助解释异常或提出关注点，不能替代预算责任与买货判断。',aiSplit:[['DATA','提供统一、可下钻的经营事实'],['SYSTEM','识别偏差并记录调整过程'],['HUMAN','决定预算、采购与买货节奏']],decisions:['先统一指标口径，再增加页面能力','筛选范围必须同时约束分子与分母','门店库存必须排除仓库，避免成本和周转虚高'],process:['梳理分散数据与业务口径','逐项对数并修复严重错误','接入计划、目标与真实查询','设计下钻、上传和调整审批','部署为买货辅助工具'],next:'记录使用频率、被采纳动作、影响金额与版本调整结果。'},
'old-stock':{thesis:'把一次性盘点表变成业务人员可以持续查询、跟进并采取动作的经营工具。',role:'业务问题拆解、信息结构、查询界面和真实使用迭代。',maturity:'已有真实业务人员使用，并形成明确的处理周期变化。',context:'老货识别依赖分散数据与人工判断，库龄、库存、销售状态和后续动作难以在同一处查看。',users:'商品运营以及负责清货、调拨、降价和库存跟进的业务人员。',solution:'将老货识别和商品明细转成可查询工具，让业务人员从发现老货继续走到经营动作，而不是重复传递静态表格。',features:['库龄、库存与销售状态统一查询','从汇总继续下钻到商品明细','为清货、调拨、降价和观察提供工作入口','可重复使用，而非一次性盘点文件'],aiTitle:'这个问题不需要先上 AI。',aiNote:'高价值动作是先把数据整合、筛选和跟进流程做稳定。AI 可以辅助归纳异常与建议下一步，但不应替代商品人员对库存和经营动作的判断。',aiSplit:[['DATA','识别老货并呈现经营状态'],['TOOL','支持查询、明细与持续跟进'],['HUMAN','选择清货、调拨或观察动作']],decisions:['同时呈现库龄、库存、销售状态和后续动作','让明细可被直接查询，而不是继续传递表格','效率结果与后续经营结果分开衡量'],process:['还原人工盘点过程','整合老货识别与商品明细','形成查询和跟进工具','交付业务人员使用','记录处理周期变化'],next:'补齐实际使用人数、覆盖商品，以及后续经营动作和库存结果。'},
catalog:{thesis:'把商品图片、属性和到货信息放进同一个可筛选视图，降低跨部门信息壁垒。',role:'商品信息架构、筛选维度、卡片视图与后续生命周期连接规划。',maturity:'已形成真实页面；使用规模和刷新机制仍待记录。',context:'每季新商品数量大，图片和属性分散，非直接经手人员很难快速知道有哪些款、长什么样以及何时到货。',users:'企划、运营、门店、市场及需要快速了解当季商品的协作角色。',solution:'把商品视觉信息与结构化属性放在同一目录，通过品牌、分类、季节、性别和到货日期等条件快速检索。',features:['商品图片、SPU、货号与价格卡片','品牌、季节、性别、颜色和尺码属性','采购组与一至三级分类筛选','到货量和首次到货日期查询'],aiTitle:'先建立统一商品视图，再讨论智能推荐。',aiNote:'目录阶段的关键是信息完整、检索准确和刷新稳定。未来 AI 可用于相似款检索或自然语言查询，但不能在基础商品主数据不稳定时抢跑。',aiSplit:[['DATA','统一图片、属性与到货信息'],['SEARCH','围绕真实任务完成筛选检索'],['AI NEXT','在可靠目录之上扩展相似款与问答']],decisions:['视觉信息和结构化属性必须在同一界面','筛选围绕真实工作任务，而不是堆叠字段','为经营表现和生命周期连接预留结构'],process:['梳理跨部门查商品任务','统一图片与关键属性','设计筛选和卡片视图','形成真实页面','规划生命周期连接'],next:'记录覆盖 SPU、刷新频率、活跃用户与典型使用任务。'},
'gap-radar':{thesis:'用内部多品牌自然样本，寻找其他组已经验证、但本组覆盖不足的需求机会。',role:'机会结构、透明计算、数据质量校验和周期化运行设计。',maturity:'完成真实数据验证与周期化设计；机会采用和经营结果仍待跟踪。',context:'企划判断容易依赖经验，外部市场数据又难取得且口径不一；内部不同品牌组已经形成可比较的自然样本。',users:'商品企划、买手及需要判断品类、价格带和商品结构机会的业务人员。',solution:'以三级品类、价格带和品牌组组织机会，识别结构、价格、供给和属性缺口，并设计月度刷新与异常预警。',features:['四类缺口结构与可配置规则','透明可复核的机会金额计算','3 个半年度、5 个品牌组的数据覆盖','总量、已知答案与复现检查','售罄分母和到货字段的专项校验'],aiTitle:'AI 用于扩大视野，不替代经营证据。',aiNote:'内部经营数据是机会判断的主体；AI 和外部资料可辅助发现盲区、整理属性与提出假设，但不能把市场想象包装成已验证需求。',aiSplit:[['DATA','验证内部品类与价格带机会'],['AI','补充外部线索并整理属性假设'],['HUMAN','决定是否进入企划与买货']],decisions:['用三级品类 × 价格带 × 品牌组组织机会','机会金额采用透明计算而非黑盒评分','外部资料只检查盲区，不替代内部证据'],process:['统一数据字典口径','建立四类缺口结构','跨周期与品牌组计算','完成数据质量校验','设计刷新和经营验证'],next:'跟踪哪些机会进入企划或买货，并验证后续销售与售罄。'},
defect:{thesis:'规则不统一时直接做系统，只会把争议、例外和责任空白固化进去。',role:'历史数据梳理、规则归并、跨部门讨论、标准确认与培训推动。',maturity:'完成标准、流程与培训；系统化后续没有持续推进。',context:'残次处理横跨门店、仓库、区域、供应商与商品管理，判定、申诉、折让、退供和考核规则并存。',users:'门店、仓库、区域、供应商管理与商品管理相关角色。',solution:'先从历史数据和规则中识别冲突，把争议拆成可拍板项和待访谈项，统一标准、责任、例外和申诉流程。',features:['约 35 万条历史记录分析','数百条规则归并与冲突识别','变价、退供、调拨、折让等规则明确','标准确认与业务培训'],aiTitle:'AI 可以帮忙整理规则，但不能代替组织拍板。',aiNote:'规则抽取和冲突聚类适合 AI 辅助；责任划分、例外政策和考核方式必须由业务共同确认。项目的关键产品判断是先治理，再数字化。',aiSplit:[['AI','辅助整理历史规则与争议线索'],['BUSINESS','确认标准、责任、例外和申诉'],['SYSTEM NEXT','在稳定规则上构建工作台']],decisions:['先统一标准，再统一流程，最后讨论数字化','把争议拆成可拍板项与待访谈项','没有持续授权时，不把规划包装成上线成果'],process:['分析历史记录','整理并分类规则','组织业务讨论与拍板','形成标准和流程','完成培训并划定后续'],next:'如重新获得正式授权，先验证标准执行，再规划数字化工作台。'},
hive:{thesis:'把准入、负责人、资源、代码、真实使用与催办串成连续的 AI 项目治理链。',role:'提出治理逻辑，设计六阶段框架，并完成本人版本的一期登记闸门基础。',maturity:'本人版本完成一期基础；后续由他人接手，完整治理链尚未全部落地。',context:'约 31 个内部 AI 项目分散推进，可能缺少统一入口、知情负责人、代码托管、使用监控与退出机制。',users:'AI 项目发起人、部门负责人、技术支持与需要掌握项目健康度的管理者。',solution:'以登记号为准入闸门，逐步连接建群、受控 AI 入口、代码提交、真实使用和 Deadline 追踪。',features:['六阶段项目治理框架','登记字段、登记号与状态机','项目登记册、身份登录与移动端基础','人员选择的搜索交互','代码、采用与 Deadline 的后续健康度设计'],aiTitle:'治理对象不是模型，而是项目责任与真实采用。',aiNote:'AI 项目能否成功，不能只看 Demo。平台需要确认谁负责、代码是否持续、是否有人使用、困难是什么，以及什么时候退出或继续投入。',aiSplit:[['GATE','立项价值、负责人和登记号'],['HEALTH','代码提交、真实使用和进度'],['GOVERNANCE','催办、资源决策与退出机制']],decisions:['没有登记号不进入下一阶段','用群成员和身份回填真实负责人','代码提交与真实使用必须进入项目健康度'],process:['形成项目章程','设计六阶段路线图','完成登记表单与状态机','搭建登记册和登录基础','划定本人版本与后续接手边界'],next:'钉钉建群、代码监控、使用埋点和 Deadline 机器人仍需正式资源实现。'},
buyflow:{thesis:'用统一状态和供应商免登录 H5，减少行政采购中的群聊追问、重复录入与跑腿对账。',role:'端到端流程、角色信息架构、异常状态、供应商协同和对账体验设计。',maturity:'高完成度 Demo；核心链路仍含模拟数据，尚未真实上线。',context:'行政采购依赖群聊追问、纸质单据和供应商跑腿，提单、审批、发货、签收与对账之间缺少统一状态。',users:'区域 HR、采购执行、审批人、供应商与签收人员。',solution:'申请后按供应商自动拆单，供应商通过有时效链接进入 H5 填写物流，采购方持续追踪异常、签收和对账。',features:['申请、审批、拆单、发货、签收和对账闭环','供应商免注册 H5 与有时效 Token','部分发货、无法接单和异常数量状态','物流追踪、二维码与对账 PDF','按角色收敛导航和信息量'],aiTitle:'流程自动化比聊天机器人更重要。',aiNote:'这个场景的核心是统一状态与减少重复操作。AI 可辅助解释申请、识别异常或生成摘要，但不应增加一个需要员工重复维护的入口。',aiSplit:[['SYSTEM','拆单、状态流转、物流与对账'],['AI OPTIONAL','摘要、异常说明与材料辅助'],['HUMAN','审批、供应商协商与异常处理']],decisions:['按首选供应商自动拆单','供应商免注册，但 Token 必须有时效和状态','不重复建设审批 UI，正式方案应穿透现有审批'],process:['还原提单到对账链路','定义角色和状态','覆盖异常与供应商协同','完成高完整度 Demo','等待真实数据和试用验证'],next:'接入真实审批、采购数据和供应商试用，并用真实计时验证效率。'},
dictionary:{thesis:'把 AI 查数不准拆成复合需求、词条选择和口径对齐三层，而不是只靠增加反问。',role:'错误链路诊断、冲突扫描、澄清策略、对抗测试和产品取舍。',maturity:'完成诊断、方案与对抗测试；部分规则仍待真实用户查询校准。',context:'用户用自然语言查数时，一个词可能命中多个指标；即使指标正确，时间、退货和粒度口径也可能被静默默认。',users:'使用自然语言查询经营数据的业务人员，以及维护数据字典和查数体验的团队。',solution:'把错误链路拆成 L0 复合需求、L1 词条选择和 L2 口径对齐，并按风险决定直接回答、默认声明或发起确认。',features:['指标索引与关键词冲突扫描','真实歧义与噪音分层','低打扰的澄清策略','对抗测试与规则修正','面向真实查询的回归评测方向'],aiTitle:'准确率和交互成本需要一起设计。',aiNote:'每次都反问会让系统安全却难用；从不确认又会静默出错。AI 负责理解语言，数据字典提供标准指标，产品策略根据风险决定何时打断。',aiSplit:[['AI','理解复合需求与用户表达'],['DICTIONARY','提供标准指标、口径和受控查询'],['UX POLICY','按风险决定默认、声明或确认']],decisions:['够具体则不打断，模糊时默认并声明，高风险才确认','理论关键词冲突必须用真实查询校准','数据权限不能寄托在提示词层'],process:['扫描指标与触发词','划分三层错误链路','设计分层澄清策略','执行对抗测试','转向真实查询评测'],next:'收集真实用户查询，建立可回归评测集并量化准确率与体验权衡。'}
};

const steps=[
{title:'先看任务如何发生',body:'理解谁在参与、信息在哪里流失。不要把一句“效率低”直接翻译成功能需求。',image:'assets/previews/step-field.webp'},
{title:'把症状、原因和结果分开',body:'明确目标、口径、角色和约束。哪些是流程问题，哪些是数据问题，哪些才需要 AI。',image:'assets/previews/step-define.webp'},
{title:'让经验变成可执行规则',body:'把隐性判断写成流程、状态、指标、例外与回滚机制，让系统能够解释结果。',image:'assets/previews/step-model.webp'},
{title:'连接数据、权限与业务动作',body:'界面不是终点。产品需要进入真实链路，让用户能发现问题并采取下一步动作。',image:'assets/previews/step-product.webp'},
{title:'用真实结果校正系统',body:'与人工答案、历史数据或实际用户对照，记录采用、删改、异常和最终经营结果。',image:'assets/previews/step-validate.webp'}
];
function renderStep(i){const s=steps[i];document.querySelector('#stepPanel').innerHTML=`<div><p class="label">STEP ${String(i+1).padStart(2,'0')}</p><h3>${s.title}</h3><p>${s.body}</p></div><div class="step-image"><img src="${s.image}" loading="lazy" decoding="async" alt="该阶段的脱敏项目界面"></div>`}

const questions=[
{q:'提示词能承担数据权限吗？',a:'不能。',text:'提示词可以解释规则，但重要权限必须进入身份、策略和查询执行链。'},
{q:'算法达到 85%，就能替代人工吗？',a:'不能直接推导。',text:'准确性随场景变化，人工复核与经营结果也必须记录。'},
{q:'做出 Demo，等于创造价值吗？',a:'不等于。',text:'Demo 证明能做，真实采用证明有用，经营结果才能证明改变。'}
];
function renderQuestions(){document.querySelector('#questionList').innerHTML=questions.map((q,i)=>`<article class="question"><span class="label">QUESTION ${String(i+1).padStart(2,'0')}</span><h3>${q.q}</h3><button data-question>Reveal my answer</button><div class="question-answer"><b>${q.a}</b><p>${q.text}</p><button data-question>Close</button></div></article>`).join('')}

let filter='all',activeIndex=0,lastFocus=null,reelIndex=0,archiveList=projects,reelFrame=0,reelSuppressClick=false,reelSettleTimer=0;
function visualMarkup(p,i,label){return p.image?`<img src="${p.image}" loading="lazy" decoding="async" alt="${p.title}经过脱敏处理的界面预览">`:`<span>${p.type.split(' / ')[0]}</span><b>${label}<br>${String(i+1).padStart(2,'0')}</b>`}
function renderArchive(){
 archiveList=projects.filter(p=>filter==='all'||p.category===filter);reelIndex=0;
 document.querySelector('#archiveCounter').textContent=`${String(archiveList.length).padStart(2,'0')} PROJECTS`;
 const reelItems=archiveList.length>1?[{project:archiveList.at(-1),index:archiveList.length-1,clone:'last'},...archiveList.map((project,index)=>({project,index,clone:''})),{project:archiveList[0],index:0,clone:'first'}]:archiveList.map((project,index)=>({project,index,clone:''}));
 document.querySelector('#reelGrid').innerHTML=reelItems.map(({project:p,index:i,clone})=>`<article class="reel-card ${!clone&&i===0?'active':''}" tabindex="${clone?'-1':'0'}" role="button" data-reel-index="${i}" ${clone?`data-reel-clone="${clone}" aria-hidden="true"`:''} data-open="${p.id}" style="--reel-accent:${p.category==='research'?'var(--lime)':p.category==='governance'?'var(--blue)':'var(--orange)'}"><span class="reel-media ${p.image?'':'typographic'}">${visualMarkup(p,i,'PROJECT')}</span><span class="reel-overlay"><span>${String(i+1).padStart(2,'0')} / ${p.status}</span><strong>${p.title}</strong><p>${p.summary}</p><b>${p.proof}</b></span></article>`).join('');
 requestAnimationFrame(()=>{const cards=[...document.querySelectorAll('#reelGrid .reel-card')],first=cards.find(card=>!card.dataset.reelClone&&card.dataset.reelIndex==='0');scrollReelCard(first,'auto');syncReel()})
}
function scrollReelCard(card,behavior='smooth'){if(!card)return;const track=document.querySelector('#reelGrid');track.scrollTo({left:card.offsetLeft-(track.clientWidth-card.offsetWidth)/2,behavior})}
function syncReel(){const track=document.querySelector('#reelGrid'),cards=[...track.querySelectorAll('.reel-card')];if(!cards.length)return;const center=track.scrollLeft+track.clientWidth/2;let nearest=0,distance=Infinity;cards.forEach((card,i)=>{const cardCenter=card.offsetLeft+card.offsetWidth/2,d=cardCenter-center,span=card.offsetWidth+parseFloat(getComputedStyle(track).gap||0),offset=Math.max(-2.2,Math.min(2.2,d/span));card.style.setProperty('--reel-offset',offset.toFixed(3));card.style.setProperty('--reel-abs',Math.abs(offset).toFixed(3));card.style.zIndex=String(20-Math.round(Math.abs(offset)*5));if(Math.abs(d)<distance){distance=Math.abs(d);nearest=i}});const activeCard=cards[nearest],realIndex=Number(activeCard.dataset.reelIndex);reelIndex=realIndex;cards.forEach((card,i)=>card.classList.toggle('active',i===nearest));const count=`${String(realIndex+1).padStart(2,'0')} / ${String(archiveList.length).padStart(2,'0')}`;document.querySelector('#reelCount').textContent=count;document.querySelector('#archiveCounter').textContent=count;document.querySelector('#reelProgress').style.transform=`scaleX(${(realIndex+1)/archiveList.length})`;clearTimeout(reelSettleTimer);reelSettleTimer=setTimeout(()=>{if(track.classList.contains('dragging')||!activeCard.dataset.reelClone)return;const target=cards.find(card=>!card.dataset.reelClone&&card.dataset.reelIndex===activeCard.dataset.reelIndex);scrollReelCard(target,'auto')},140)}
function text(id,value){document.querySelector(id).textContent=value}
const interactiveDemos={ctc:{src:'demos/ctc-bundle.html?v=18',path:'demo.local/ctc/run'},otb:{src:'demos/otb-bundle.html?v=18',path:'demo.local/otb/overview'},'gap-radar':{src:'demos/gap-radar-bundle.html?v=18',path:'demo.local/assortment/opportunities'},buyflow:{src:'demos/buyflow.html?v=21',path:'demo.local/buyflow/purchase/new'}};
function caseVisual(p,i){const demo=interactiveDemos[p.id];if(demo)return `<div class="demo-browser"><div class="browser-tabs"><span class="browser-dots"><i></i><i></i><i></i></span><span class="browser-tab">${p.title}<b>×</b></span><button data-demo-action="reload" aria-label="重置 Demo">↻</button></div><div class="browser-bar"><span>‹</span><span>›</span><button data-demo-action="reload" aria-label="刷新 Demo">↻</button><div><i>◆</i>${demo.path}</div><button data-demo-action="open" data-demo-src="${demo.src}">全屏打开 ↗</button></div><div class="browser-note"><b>INTERACTIVE DEMO</b><span>全部为虚构数据，可直接操作</span></div><div class="demo-loading"><i></i><b>正在加载交互 Demo</b><span>首次打开需要片刻</span><button data-demo-action="open" data-demo-src="${demo.src}">直接打开 ↗</button></div><iframe src="${demo.src}" title="${p.title}交互演示" loading="eager" onload="const browser=this.closest('.demo-browser');browser.classList.add('demo-ready');browser.querySelector('.demo-loading')?.remove()"></iframe></div>`;return p.image?`<img src="${p.image}" loading="eager" decoding="async" alt="${p.title}界面节选"><figcaption>PRODUCT INTERFACE / SELECTED VIEW</figcaption>`:`<div class="case-type-cover" style="--case-accent:${p.category==='research'?'var(--lime)':p.category==='governance'?'var(--blue)':'var(--orange)'}"><span>${p.type}</span><b>CASE<br>${String(i+1).padStart(2,'0')}</b><small>${p.status}</small></div>`}
function list(id,items){document.querySelector(id).innerHTML=items.map(x=>`<li>${x}</li>`).join('')}
function openDetail(id,source,updateRoute=true){const i=projects.findIndex(p=>p.id===id);if(i<0)return;activeIndex=i;lastFocus=source||lastFocus;const p=projects[i],d=caseDetails[id],next=projects[(i+1)%projects.length];text('#detailCount',`${String(i+1).padStart(2,'0')} / ${projects.length}`);text('#detailType',p.type);text('#detailTitle',p.title);text('#detailSummary',p.summary);text('#detailStatus',p.status);text('#detailProof',p.proof);text('#detailProofLarge',p.proof);text('#detailProblem',p.problem);text('#detailEvidence',p.evidence);text('#detailBoundary',p.boundary);text('#detailThesis',d.thesis);text('#detailRole',d.role);text('#detailMaturity',d.maturity);text('#detailContext',d.context);text('#detailUsers',d.users);text('#detailSolution',d.solution);text('#detailAiTitle',d.aiTitle);text('#detailAiNote',d.aiNote);text('#detailNextStep',d.next);text('#detailNextTitle',next.title);list('#detailFeatures',d.features);list('#detailWork',p.work);list('#detailDecisions',d.decisions);list('#detailProcess',d.process);document.querySelector('#detailAiSplit').innerHTML=d.aiSplit.map(([label,body])=>`<div><span>${label}</span><p>${body}</p></div>`).join('');document.querySelector('#detailVisual').innerHTML=caseVisual(p,i);document.querySelector('#detailNextCase').dataset.next=next.id;const detail=document.querySelector('#detail');detail.classList.add('open');detail.setAttribute('aria-hidden','false');detail.scrollTop=0;document.body.style.overflow='hidden';if(updateRoute&&location.hash!==`#case=${id}`)history.pushState({case:id},'',`#case=${id}`)}
function closeDetail(updateRoute=true){const detail=document.querySelector('#detail');detail.classList.remove('open');detail.setAttribute('aria-hidden','true');document.body.style.overflow='';if(updateRoute&&location.hash.startsWith('#case='))history.replaceState({},'',location.pathname+location.search);setTimeout(()=>lastFocus?.focus(),50)}
function syncCaseRoute(){const match=location.hash.match(/^#case=([\w-]+)$/);if(match&&projects.some(p=>p.id===match[1]))openDetail(match[1],null,false);else if(document.querySelector('#detail').classList.contains('open'))closeDetail(false)}

document.addEventListener('click',e=>{
 const demoAction=e.target.closest('[data-demo-action]');if(demoAction){const browser=demoAction.closest('.demo-browser'),frame=browser?.querySelector('iframe');if(demoAction.dataset.demoAction==='reload'&&frame)frame.src=frame.src;if(demoAction.dataset.demoAction==='open')window.open(demoAction.dataset.demoSrc,'_blank','noopener');return}
 const step=e.target.closest('[data-step]');if(step){document.querySelectorAll('.step').forEach(x=>x.classList.toggle('active',x===step));renderStep(Number(step.dataset.step))}
 const question=e.target.closest('[data-question]');if(question)question.closest('.question').classList.toggle('open');
 const impact=e.target.closest('.impact-card');if(impact&&!e.target.closest('[data-open]'))activateInGroup('.impact-card',impact);
 const strength=e.target.closest('.strength-rail');if(strength){document.querySelectorAll('.strength-rail').forEach(x=>x.classList.toggle('active',x===strength))}
 const f=e.target.closest('[data-filter]');if(f){filter=f.dataset.filter;document.querySelectorAll('.filters button').forEach(x=>x.classList.toggle('active',x===f));renderArchive()}
 const reel=e.target.closest('[data-reel-index]');if(reel&&reelSuppressClick){reelSuppressClick=false;return}
 const open=e.target.closest('[data-open]');if(open)openDetail(open.dataset.open,open);
});
document.querySelector('#detailClose').addEventListener('click',()=>closeDetail());document.querySelector('#detailPrev').addEventListener('click',()=>openDetail(projects[(activeIndex-1+projects.length)%projects.length].id));document.querySelector('#detailNext').addEventListener('click',()=>openDetail(projects[(activeIndex+1)%projects.length].id));document.querySelector('#detailNextCase').addEventListener('click',e=>openDetail(e.currentTarget.dataset.next));window.addEventListener('popstate',syncCaseRoute);window.addEventListener('hashchange',syncCaseRoute);
function activateInGroup(selector,target){document.querySelectorAll(selector).forEach(x=>x.classList.toggle('active',x===target))}
document.querySelectorAll('.impact-card').forEach(card=>{card.addEventListener('pointerenter',()=>activateInGroup('.impact-card',card));card.addEventListener('focusin',()=>activateInGroup('.impact-card',card))});
document.querySelectorAll('.strength-rail').forEach(rail=>{rail.addEventListener('pointerenter',()=>activateInGroup('.strength-rail',rail));rail.addEventListener('focusin',()=>activateInGroup('.strength-rail',rail))});

const reelGrid=document.querySelector('#reelGrid');let reelDrag=null;
function endReelDrag(e){if(!reelDrag)return;const moved=reelDrag.moved,pointerId=reelDrag.pointerId;if(reelGrid.hasPointerCapture(pointerId))reelGrid.releasePointerCapture(pointerId);reelDrag=null;reelGrid.classList.remove('dragging');if(moved)setTimeout(()=>{reelSuppressClick=false},0)}
reelGrid.addEventListener('scroll',()=>{cancelAnimationFrame(reelFrame);reelFrame=requestAnimationFrame(syncReel)});
reelGrid.addEventListener('pointerdown',e=>{if(e.button!==0&&!['touch','pen'].includes(e.pointerType))return;const card=e.target.closest('.reel-card');if(!card)return;reelDrag={x:e.clientX,scroll:reelGrid.scrollLeft,pointerId:e.pointerId,moved:false}});
reelGrid.addEventListener('pointermove',e=>{if(!reelDrag||e.pointerId!==reelDrag.pointerId)return;const dx=e.clientX-reelDrag.x;if(!reelDrag.moved&&Math.abs(dx)>6){reelDrag.moved=true;reelSuppressClick=true;reelGrid.classList.add('dragging');reelGrid.setPointerCapture(e.pointerId)}if(reelDrag.moved)reelGrid.scrollLeft=reelDrag.scroll-dx});
reelGrid.addEventListener('pointerup',endReelDrag);reelGrid.addEventListener('pointercancel',endReelDrag);
reelGrid.addEventListener('keydown',e=>{const card=e.target.closest('.reel-card:not([data-reel-clone])');if(card&&['Enter',' '].includes(e.key)){e.preventDefault();openDetail(card.dataset.open,card);return}if(!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();const cards=[...reelGrid.querySelectorAll('.reel-card:not([data-reel-clone])')],current=Math.max(0,cards.indexOf(document.activeElement)),next=Math.max(0,Math.min(cards.length-1,current+(e.key==='ArrowRight'?1:-1)));scrollReelCard(cards[next]);cards[next].focus({preventScroll:true})});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('#detail').classList.contains('open'))closeDetail()});document.querySelector('#themeToggle').addEventListener('click',()=>document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark');
renderStep(0);renderQuestions();renderArchive();syncCaseRoute();
